name: nlp
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.7.0
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pip
  - setuptools
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - lightning
  - torchmetrics
  - torchinfo
  - wandb
  - scipy
  - ray-tune
  - optuna
  - cuda-nvcc
  - numpy
  - pandas
  - matplotlib
  - bokeh
  - seaborn
  - jupyter
  - jupyterlab
  - ipython
  - ipywidgets
  - datasets
  - transformers
  - tokenizers
  - tensorboard
  - gradio
  - streamlit
  - onnx
  - onnxruntime
  - opencv
  - imgaug
  - albumentations
  - tqdm
  - pip:
      - pyyaml==5.3.1
      - selectivesearch
      - gradient
      - "black[jupyter]"
      - flake8
      - torch-tb-profiler
      - click
